### ISSUE TITLE
ValueError: day is out of range for month at standing order

### ISSUE THREAD

**Issue by dmkif** [SebastianRzk/BudgetButlerWeb#174]
After I created a standing order, Budgetbuttler (offline) is no longer accessible. 
Before that I get the following error message:

![grafik](https://user-images.githubusercontent.com/18344002/167075792-cba91dc7-c0ab-48db-af99-325da0c80b70.png)

It must be checked for a standing order if the date is in the month and if not, set it to the last of the month (e.g. February 28).

Here my logoutput:
```
 * Serving Flask app 'start_as_flask.py' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://10.255.2.10:5000 (Press CTRL+C to quit)
10.255.2.11 - - [06/May/2022 07:58:07] "GET / HTTP/1.1" 200 -
10.255.2.11 - - [06/May/2022 07:58:07] "GET /static/theme/chartjs/Chart.min.js HTTP/1.1" 200 -
10.255.2.11 - - [06/May/2022 07:58:07] "GET /static/theme/bootstrap/bootstrap.min.css HTTP/1.1" 200 -
10.255.2.11 - - [06/May/2022 07:58:07] "GET /static/theme/font-awesome/font-awesome.min.css HTTP/1.1" 200 -
10.255.2.11 - - [06/May/2022 07:58:07] "GET /static/theme/butler_menu.js HTTP/1.1" 200 -
10.255.2.11 - - [06/May/2022 07:58:07] "GET /static/theme/butler_box.js HTTP/1.1" 200 -
10.255.2.11 - - [06/May/2022 07:58:07] "GET /static/theme/theme.css HTTP/1.1" 200 -
10.255.2.11 - - [06/May/2022 07:58:07] "GET /theme/ HTTP/1.1" 200 -
10.255.2.11 - - [06/May/2022 07:58:13] "GET /adddauerauftrag/ HTTP/1.1" 200 -
10.255.2.11 - - [06/May/2022 07:58:13] "GET /static/theme/butler_box.js HTTP/1.1" 304 -
10.255.2.11 - - [06/May/2022 07:58:13] "GET /static/theme/chartjs/Chart.min.js HTTP/1.1" 304 -
10.255.2.11 - - [06/May/2022 07:58:13] "GET /static/theme/butler_menu.js HTTP/1.1" 304 -
10.255.2.11 - - [06/May/2022 07:58:13] "GET /static/theme/font-awesome/font-awesome.min.css HTTP/1.1" 304 -
10.255.2.11 - - [06/May/2022 07:58:13] "GET /static/theme/theme.css HTTP/1.1" 304 -
10.255.2.11 - - [06/May/2022 07:58:13] "GET /static/theme/bootstrap/bootstrap.min.css HTTP/1.1" 200 -
10.255.2.11 - - [06/May/2022 07:58:13] "GET /theme/ HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/butler/butler_offline/viewcore/request_handler.py", line 39, in handle_request
    persisted_state.save_tainted()
  File "/home/butler/butler_offline/viewcore/state/persisted_state.py", line 52, in save_tainted
    _save_refresh()
  File "/home/butler/butler_offline/viewcore/state/persisted_state.py", line 45, in _save_refresh
    switch_database_instance(db_name)
  File "/home/butler/butler_offline/viewcore/state/persisted_state.py", line 33, in switch_database_instance
    persisted_state.DATABASE_INSTANCE = database_manager.read(database_name, ausgeschlossene_kategorien=ausgeschlossene_kategorien)
  File "/home/butler/butler_offline/core/database_manager.py", line 68, in read
    database.refresh()
  File "/home/butler/butler_offline/core/database/__init__.py", line 57, in refresh
    alle_dauerauftragsbuchungen = self.dauerauftraege.get_all_einzelbuchungen_until_today()
  File "/home/butler/butler_offline/core/database/dauerauftraege.py", line 40, in get_all_einzelbuchungen_until_today
    dauerauftrag_buchungen = self.einnahmenausgaben_until_today(
  File "/home/butler/butler_offline/core/database/dauerauftraege.py", line 34, in einnahmenausgaben_until_today
    laufdatum = frequency_function(laufdatum)
  File "/home/butler/butler_offline/core/frequency.py", line 6, in _add_month
    datum = date(day=datum.day, month=(datum.month + 1), year=datum.year)
ValueError: day is out of range for month
10.255.2.11 - - [06/May/2022 07:58:40] "POST /adddauerauftrag/ HTTP/1.1" 200 -
10.255.2.11 - - [06/May/2022 07:58:40] "GET /static/theme/bootstrap/bootstrap.min.css HTTP/1.1" 304 -
10.255.2.11 - - [06/May/2022 07:58:40] "GET /static/theme/font-awesome/font-awesome.min.css HTTP/1.1" 304 -
10.255.2.11 - - [06/May/2022 07:58:40] "GET /static/theme/theme.css HTTP/1.1" 304 -
10.255.2.11 - - [06/May/2022 07:58:40] "GET /static/theme/butler_box.js HTTP/1.1" 304 -
10.255.2.11 - - [06/May/2022 07:58:40] "GET /static/theme/butler_menu.js HTTP/1.1" 304 -
10.255.2.11 - - [06/May/2022 07:58:40] "GET /static/theme/chartjs/Chart.min.js HTTP/1.1" 304 -
10.255.2.11 - - [06/May/2022 07:58:40] "GET /theme/ HTTP/1.1" 200 -
[2022-05-06 07:58:46,960] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/butler/.local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/butler/.local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/butler/.local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/butler/.local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/butler/butler_offline/start_as_flask.py", line 46, in show_dashboard
    return dashboard.index(request)
  File "/home/butler/butler_offline/views/core/dashboard.py", line 52, in index
    return request_handler.handle_request(request, _handle_request, 'core/dashboard.html')
  File "/home/butler/butler_offline/viewcore/request_handler.py", line 36, in handle_request
    context = viewcore.generate_base_context('Fehler')
  File "/home/butler/butler_offline/viewcore/viewcore.py", line 10, in generate_base_context
    'active': get_key_for_name(pagename),
  File "/home/butler/butler_offline/viewcore/menu.py", line 46, in get_key_for_name
    for name, menu_items in get_menu_list().items():
  File "/home/butler/butler_offline/viewcore/menu.py", line 95, in get_menu_list
    menu.append({'url': '/production/?database=' + persisted_state.database_instance().name,
  File "/home/butler/butler_offline/viewcore/state/persisted_state.py", line 20, in database_instance
    persisted_state.DATABASE_INSTANCE = database_manager.read(persisted_state.DATABASES[0],
  File "/home/butler/butler_offline/core/database_manager.py", line 68, in read
    database.refresh()
  File "/home/butler/butler_offline/core/database/__init__.py", line 57, in refresh
    alle_dauerauftragsbuchungen = self.dauerauftraege.get_all_einzelbuchungen_until_today()
  File "/home/butler/butler_offline/core/database/dauerauftraege.py", line 40, in get_all_einzelbuchungen_until_today
    dauerauftrag_buchungen = self.einnahmenausgaben_until_today(
  File "/home/butler/butler_offline/core/database/dauerauftraege.py", line 34, in einnahmenausgaben_until_today
    laufdatum = frequency_function(laufdatum)
  File "/home/butler/butler_offline/core/frequency.py", line 6, in _add_month
    datum = date(day=datum.day, month=(datum.month + 1), year=datum.year)
ValueError: day is out of range for month
10.255.2.11 - - [06/May/2022 07:58:46] "GET / HTTP/1.1" 500 -
```

Steps to reproduce:

- add standing order e.g. start 31. January end 15. March
- error occurs -> Budgetbutler isn´t accessible until fixing the database entry

**Comment by SebastianRzk** [comment]
If the last possible month date is before the standing order date, the last day of the month is used as the posting date.


E.g.:
Standing order on the 31st of the month:
*  31 Januar
*  28 Feburar

**Comment by SebastianRzk** [comment]
Test: test.core.database.dauerauftraege_test::test_get_einzelbuchungen_until_today_should_use_end_of_month_when_overflow
